import com.liferay.gradle.plugins.node.task.ExecuteNodeScriptTask

import org.apache.tools.ant.types.Commandline

buildscript {
	dependencies {
		classpath group: "com.liferay", name: "com.liferay.gradle.plugins.defaults", version: "latest.release"
	}

	repositories {
		mavenLocal()

		maven {
			url "https://repository-cdn.liferay.com/nexus/content/groups/public"
		}
	}
}

apply plugin: "com.liferay.node"

node {
	nodeVersion = "20.12.2"
}

task runPlaywright(type: ExecuteNodeScriptTask)

runPlaywright {
	def playwrightArgs = project.property("playwright.args")

	if (playwrightArgs != null) {
		args Commandline.translateCommandline(playwrightArgs)
	}

	dependsOn "npmInstall"
	scriptFile = "node_modules/.bin/playwright"
}